
SET(FFTW3_INCLUDE_SEARCH_PATH

	/usr/include
	/usr/include/fftw
	/usr/local/include
	/usr/local/include/fftw
	C:/users/Arun/Research/fftw/include
	)

SET(FFTW3_LIB_SEARCH_PATH

	/usr/lib
	/usr/lib/fftw
	/usr/local/lib
	/usr/local/lib/fftw
	C:/users/Arun/Research/fftw/lib
	)

FIND_PATH(FFTW3_INCLUDE_PATH fftw3.h ${FFTW3_INCLUDE_SEARCH_PATH})

IF(FFTW3_INCLUDE_PATH)
	SET(FFTW3_INCLUDE_DIR ${FFTW3_INCLUDE_PATH})
ENDIF(FFTW3_INCLUDE_PATH)


FIND_LIBRARY(FFTW3_LIB_SEARCH 
	NAMES fftw3 libfftw3 libfftw3-3
	PATHS ${FFTW3_LIB_SEARCH_PATH})

FIND_LIBRARY(FFTW3F_LIB_SEARCH 
	NAMES fftw3f libfftw3f libfftw3f-3
	PATHS ${FFTW3_LIB_SEARCH_PATH})

FIND_LIBRARY(FFTW3L_LIB_SEARCH 
	NAMES fftw3l libfftw3f libfftw3l-3
	PATHS ${FFTW3_LIB_SEARCH_PATH})


IF(FFTW3_LIB_SEARCH) #assuming that if you find one, you'd find the rest in the same place
	
	SET(FFTW3_LIBRARIES ${FFTW3_LIB_SEARCH} ${FFTW3F_LIB_SEARCH} ${FFTW3L_LIB_SEARCH})
	SET(FFTW3_FOUND TRUE)
	GET_FILENAME_COMPONENT(FFTW3_LINK_DIRECTORIES ${FFTW3_LIB_SEARCH} PATH)
	MESSAGE("Debug: FFTW3_LIBRARIES=${FFTW3_LIBRARIES}")
	MESSAGE("Debug: FFTW3_LINK_DIRECTORIES=${FFTW3_LINK_DIRECTORIES}")
	MESSAGE("Debug: FFTW3_INCLUDE_DIR=${FFTW3_INCLUDE_DIR}")
ELSE(FFTW3_LIB_SEARCH)
	MESSAGE("Could not find FFTW3 anywhere.")
ENDIF(FFTW3_LIB_SEARCH)


MARK_AS_ADVANCED(
	FFTW3_INCLUDE_DIR
	FFTW3_LIBRARIES
	FFTW3_LINK_DIRECTORIES)

