SET(CTEST_SOURCE_NAME "src/vxl")
SET(CTEST_BINARY_NAME "bin/vxl-nightly")
SET(CTEST_DASHBOARD_ROOT "C:/dashboard")
SET(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_SOURCE_NAME}")
SET(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_BINARY_NAME}")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET(CTEST_COMMAND
  "\"c:/Program Files (x86)/CMake 2.8/bin/ctest.exe\" -V -VV -D Nightly -A \"${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}\""
  )

SET(CTEST_CMAKE_COMMAND
  "\"c:/Program Files (x86)/CMake 2.8/bin/cmake.exe\""
  )

SET( CMPLR_PATH "C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/devenv.com" )
SET( VPROJ_PATH "C:/dashboard/bin/vxl-nightly/vxl.sln" )
SET( PRLL_STR_CXX "/DWIN32 /D_WINDOWS /W3 /Zm1000 /EHsc /GR /MP16" )
SET( PRLL_STR_C "/DWIN32 /D_WINDOWS /W3 /Zm1000 /MP16" )

SET(CTEST_INITIAL_CACHE "
SITE:STRING=farsight-win_7_64
BUILDNAME:STRING=vs9-64-dbg-nightly
CMAKE_GENERATOR:INTERNAL=Visual Studio 9 2008 Win64
MAKECOMMAND:STRING=${CMPLR_PATH} ${VPROJ_PATH} /build Debug /project ALL_BUILD
CMAKE_CXX_FLAGS:STRING=${PRLL_STR_CXX}
CMAKE_C_FLAGS:STRING=${PRLL_STR_C}
BUILD_BRL:BOOL=OFF
BUILD_CONVERSIONS:BOOL=OFF
BUILD_EXAMPLES:BOOL=OFF
BUILD_GEL:BOOL=OFF
BUILD_OUL:BOOL=OFF
BUILD_OXL:BOOL=OFF
BUILD_PRIP:BOOL=OFF
BUILD_TBL:BOOL=OFF
BUILD_TESTING:BOOL=ON
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_BRL:BOOL=OFF
BUILD_RPL_RGTL:BOOL=ON
BUILD_RPL_RTVL:BOOL=ON
")

SET(CTEST_CVS_COMMAND "C:/Program Files/TortoiseSVN/bin/TortoiseProc.exe")
