SET(CTEST_SOURCE_NAME farsight-trunk)
SET(CTEST_BINARY_NAME farsight-nightly-debug-makefiles)
SET(CTEST_DASHBOARD_ROOT "/projects/Dashboards")
SET(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_SOURCE_NAME}")
SET(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_BINARY_NAME}")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET(CTEST_COMMAND
  "/usr/local/bin/ctest -V -VV -D Nightly -A ${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}"
  )

SET(CTEST_CMAKE_COMMAND
  "/usr/local/bin/cmake"
  )

SET(CTEST_INITIAL_CACHE "
SITE:STRING=farsight-mac-1
BUILDNAME:STRING=nightly-debug-makefiles
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
MAKECOMMAND:STRING=/usr/bin/make -j3 -i
CMAKE_BUILD_TYPE:STRING=Debug
BUILD_SHARED_LIBS:BOOL=OFF
ITK_DIR:PATH=/Users/isaac/ITK/bin
VTK_DIR:PATH=/Users/isaac/VTK/binNightly
CMAKE_OSX_ARCHITECTURES:STRING=i386
")

SET(CTEST_CVS_COMMAND "/usr/bin/svn")

