SET(CTEST_SOURCE_NAME itk)
SET(CTEST_BINARY_NAME itk-nightly-dbg)
SET(CTEST_DASHBOARD_ROOT "/home/gramak/dashboard")
SET(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_SOURCE_NAME}")
SET(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_BINARY_NAME}")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET(CTEST_COMMAND
  "/usr/local/bin/ctest -V -VV -D Nightly -A ${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}"
)

SET(CTEST_CMAKE_COMMAND
"/usr/local/bin/cmake"
)

SET(CTEST_INITIAL_CACHE "
SITE:STRING=farsight-opensuse
BUILDNAME:STRING=gcc45-x86_64-nightly-debug
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
MAKECOMMAND:STRING=/usr/bin/make -i -j16
CMAKE_BUILD_TYPE:STRING=Debug
VXL_DIR:STRING=/home/gramak/dashboard/vxl-nightly-dbg
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_EXAMPLES:BOOL=ON
BUILD_DOXYGEN:BOOL=OFF
BUILD_TESTING:BOOL=ON
ITK_USE_SYSTEM_VXL:BOOL=ON
ITK_USE_REVIEW:BOOL=ON
ITK_BUILD_ALL_MODULES:BOOL=ON
ITK_USE_64BITS_IDS:BOOL=ON
")

SET(CTEST_CVS_COMMAND "/usr/bin/git")
