SET(CTEST_SOURCE_NAME vxl)
SET(CTEST_BINARY_NAME vxl-nightly-dbg)
SET(CTEST_DASHBOARD_ROOT "/home/gramak/dashboard")
SET(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_SOURCE_NAME}")
SET(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_BINARY_NAME}")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET(CTEST_COMMAND
  "/usr/local/bin/ctest -V -VV -D Nightly -A ${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}"
)

SET(CTEST_CMAKE_COMMAND
"/usr/local/bin/cmake"
)

SET(CTEST_INITIAL_CACHE "
SITE:STRING=farsight-opensuse
BUILDNAME:STRING=gcc45-x86_64-nightly-debug
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
MAKECOMMAND:STRING=/usr/bin/make -i -j16
CMAKE_BUILD_TYPE:STRING=Debug
BUILD_BRL:BOOL=OFF
BUILD_CONVERSIONS:BOOL=OFF
BUILD_EXAMPLES:BOOL=OFF
BUILD_GEL:BOOL=OFF
BUILD_OUL:BOOL=OFF
BUILD_OXL:BOOL=OFF
BUILD_PRIP:BOOL=OFF
BUILD_TBL:BOOL=OFF
BUILD_TESTING:BOOL=ON
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_BRL:BOOL=OFF
BUILD_RPL_RGTL:BOOL=ON
BUILD_RPL_RTVL:BOOL=ONBUILD_SHARED_LIBS:BOOL=OFF
")

SET(CTEST_CVS_COMMAND "/usr/bin/svn")
