SET(CTEST_SOURCE_NAME vtk)
SET(CTEST_BINARY_NAME vtk-nightly-dbg)
SET(CTEST_DASHBOARD_ROOT "/home/gramak/dashboard")
SET(CTEST_SOURCE_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_SOURCE_NAME}")
SET(CTEST_BINARY_DIRECTORY "${CTEST_DASHBOARD_ROOT}/${CTEST_BINARY_NAME}")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET(CTEST_COMMAND
  "/usr/local/bin/ctest -V -VV -D Nightly -A ${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}"
)

SET(CTEST_CMAKE_COMMAND
"/usr/local/bin/cmake"
)

SET(CTEST_INITIAL_CACHE "
SITE:STRING=farsight-opensuse
BUILDNAME:STRING=gcc45-x86_64-use-boost-svn
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
MAKECOMMAND:STRING=/usr/bin/make -i -j16
CMAKE_BUILD_TYPE:STRING=Debug
VXL_DIR:STRING=/home/gramak/dashboard/vxl-nightly-dbg
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_EXAMPLES:BOOL=ON
BUILD_DOXYGEN:BOOL=OFF
BUILD_TESTING:BOOL=ON
Boost_INCLUDE_DIR:STRING=/home/gramak/dashboard/boost
VTK_USE_GUISUPPORT:BOOL=ON
VTK_USE_QT:BOOL=ON
VTK_USE_QTCHARTS:BOOL=ON
VTK_USE_BOOST:BOOL=ON
")

SET(CTEST_CVS_COMMAND "/usr/bin/git")
