#SET(OpenSlide_SOURCE_DIR "" CACHE PATH "Openslide source directory")
#SET(OpenSlide_BINARY_DIR "" CACHE PATH "Openslide binary directory")

FIND_PATH(OPENSLIDE_INCLUDE_DIR
	NAMES openslide.h
	PATHS /data/research/source/openslide/src )
#	HINTS ${OpenSlide_SOURCE_DIR}

FIND_PATH(OPENSLIDE_BINARY_DIR
        FILE libopenslide.a
        PATHS /data/research/bin/openslide/lib )
#       HINTS ${OpenSlide_BINARY_DIR}/lib

FIND_LIBRARY(OPENSLIDE_LIBRARY
	NAMES openslide
	PATHS /data/research/bin/openslide/lib )
#	HINTS ${OpenSlide_BINARY_DIR}/lib

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENSLIDE DEFAULT_MSG OPENSLIDE_LIBRARY OPENSLIDE_INCLUDE_DIR OPENSLIDE_BINARY_DIR)

IF(OPENSLIDE_FOUND)
	SET(OPENSLIDE_LIBRARY ${OPENSLIDE_LIBRARY} )
	SET(OPENSLIDE_INCLUDE_DIR ${OPENSLIDE_INCLUDE_DIR} )
	SET(OPENSLIDE_BINARY_DIR ${OPENSLIDE_BINARY_DIR} )
ENDIF(OPENSLIDE_FOUND)

MARK_AS_ADVANCED(OPENSLIDE_LIBRARY OPENSLIDE_INCLUDE_DIR OPENSLIDE_BINARY_DIR)
